### ISSUE TITLE
Hosts style mapping

### ISSUE THREAD

**Issue by Gachl** [Gachl/Virtual-Hosts-Chrome-Extension#3]
Instead of fixed single rewriting of the Host, a Hosts stile mapping table would be very useful.

myvhost.example.com  192.168.178.142
myothervhost.example.com 192.168.1.99

This way only requests to a specific IP will be affected by the Host header.

**Comment by Zacqary** [comment]
Made some progress on this here: https://github.com/Zacqary/Virtual-Hosts-Chrome-Extension/tree/url-mapping

This uses a redirect, allowing you to type in `myvhost.example.com` and redirect it to 192.168.178.142, instead of vice versa. Feels more like an actual edited hosts file this way, and allows for mapping multiple vhosts to the same IP. No table yet, still only a single host to IP mapping, but it's progress.

The only issue that I can't seem to get around is preventing the browser from changing the URL in the address bar. Chrome probably doesn't allow that for security reasons. I'll look into the APIs for adding icons to the address bar to see if those help. As long as there's some visual indicator that a virtual host is being mapped to the URL in the address bar, it shouldn't be too much of a limitation.

**Comment by Gachl** [comment]
I would like to note that I understood the hosts style mapping to only affect the Host header, not (DNS) redirecting. It works based on the functionality of the extension (Host http header overwriting), not on the functionality of the hosts file (DNS resolve mapping).

A workflow example:
1. Enter "192.168.1.116 test.example.com" in the mapping field
2. Visit dev.example.com pointing to 192.168.1.116 (by DNS or hosts)
3. dev.example.com resolves to 192.168.1.116 matching rule from 1. rewriting Host to test.example.com instead of dev.example.com

I thought of this extension more of a vhost tester/overwriter rather than a browser controlled hosts file. I'm now not sure any more what people were asking for.

I'd like to thank you for your fork and edits but I think it would make sense to split this off into a new extension, simulating hosts file behaviour and keep it separate from the Host header overwriting.

**Comment by Gachl** [comment]
Overwriting the Host header in Chrome is not possible anymore.

The plugin was rewritten to work with Firefox and support multiple hosts.

https://addons.mozilla.org/firefox/addon/vhost-simulator/
